### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by adminlove520** [insoxin/a#2]
您好 服务挂了  报502  麻烦看下

**Comment by ghost** [comment]
好像又倒了。。。邮箱联系不到您
![image](https://user-images.githubusercontent.com/32920883/206957341-18520b07-4362-4004-a462-6679700ebec8.png)
a.pages.dev的报错：
![image](https://user-images.githubusercontent.com/32920883/206957445-7dce493f-aa84-44ae-b02d-052f61ebd803.png)

**Comment by insoxin** [comment]
对的,但不是我主动关的,是腾讯说色情违规……申诉不给过

**Comment by insoxin** [comment]
我更新换下国外的域名吧

**Comment by insoxin** [comment]
需要今晚了

**Comment by ghost** [comment]
恩恩   爬虫那边估计也得处理 报10054 可能源站更新机制了吧  可以给个邮箱嘛 之前那个发不过去邮件了

**Comment by insoxin** [comment]
> 恩恩 爬虫那边估计也得处理 报10054 可能源站更新机制了吧 可以给个邮箱嘛 之前那个发不过去邮件了

因为域名被封了…… 腾讯企业邮箱也挂了

**Comment by insoxin** [comment]
> 恩恩 爬虫那边估计也得处理 报10054 可能源站更新机制了吧 可以给个邮箱嘛 之前那个发不过去邮件了

更新了解析 

等缓存就行了

```
{
  "id": "f9zcKE6KkjLxwoSy",
  "status": "finished",
  "timestamp": "2022-12-12T08:58:44.482Z",
  "paths": {
    "/": {
      "throttled": false,
      "providers": {
        "CF": true,
        "FY": true,
        "GC": true
      }
    }
  }
}

```

**Comment by insoxin** [comment]
刚试了下,全国可以了

**Comment by ghost** [comment]
doctor镜像的话  重新拉一次?

**Comment by insoxin** [comment]
> doctor镜像的话 重新拉一次?

我忘了当时打包引用的哪里了js 了

你看下[inso_img.js](https://fastly.jsdelivr.net/gh/insoxin/bz@main/bz_js/inso_img.js)  是引用哪里的,如果远程就自动更新,如果本地,告诉我一声,我再打包一份

**Comment by ghost** [comment]
https://gcore.jsdelivr.net/gh/insoxin/bz@main/bz_js/inso_img.js
应该自动更新的  远端地址

**Comment by insoxin** [comment]
> https://gcore.jsdelivr.net/gh/insoxin/bz@main/bz_js/inso_img.js 应该自动更新的 远端地址

那你可以了吗?

**Comment by insoxin** [comment]
> https://gcore.jsdelivr.net/gh/insoxin/bz@main/bz_js/inso_img.js 应该自动更新的 远端地址

如果你会搭建nginx 或apache等, 直接下载https://github.com/insoxin/a 这个 源码使用即可,很轻量  应该比docker简单多了

**Comment by adminlove520** [comment]
又报错了  这次521  感觉又被封域名了

**Comment by insoxin** [comment]
> 您好 服务挂了 报502 麻烦看下

我试了下正常啊,你f5刷新一下

**Comment by ghost** [comment]
您好  又倒了2333

**Comment by insoxin** [comment]
> 您好 又倒了2333

我试了正常啊,我这个用了cloudflare cdn 见部分地区拦截了这个cdn

**Comment by ghost** [comment]
师傅  又挂啦  方便看一下吗
